### ISSUE TITLE
Discussion for validation of config

### ISSUE THREAD

**Issue by vsoch** [bloodorangeio/reggie#24]
This [line](https://github.com/bloodorangeio/reggie/blob/master/client.go#L49) notes that we should do validation of the client config after populating options, and it would be good if this validation is consistent between Reggie here and "reggie-python" I'm currently putting together. So far, I'm thinking these are the basic needs:

 - **required fields**: the client config absolutely should have an address and a user agent.
 - **address**: the address starts with http (or other regular expression for a valid url)

The other fields are specific to authentication, debug, or similar, so I don't think there is any basic validation to do, at least on init.

**Comment by jdolitsky** [comment]
@vsoch - I think address and user-agent are good place to start. 

Here are some cross-language tips for URL validation: https://urlregex.com/

Wasn't able to find whats valid for user agent: https://tools.ietf.org/html/rfc7231#section-5.5.3

Maybe we just check it is non-empty?

**Comment by vsoch** [comment]
> Maybe we just check it is non-empty?

I think that's reasonable! I'll add it to the client I'm working on, and can try a PR here after the client is finished.
