### ISSUE TITLE
Question: digest for config in README

### ISSUE THREAD

**Issue by vsoch** [bloodorangeio/reggie#26]
This is a tiny detail, but for the README example it shows setting the blobDigest to be the config digest:

```
manifest := []byte(fmt.Sprintf(
		"{ \"mediaType\": \"application/vnd.oci.image.manifest.v1+json\", \"config\":  { \"digest\": \"%s\", "+
			"\"mediaType\": \"application/vnd.oci.image.config.v1+json\","+" \"size\": %d }, \"layers\": [], "+
			"\"schemaVersion\": 2 }",
		blobDigest, len(blob)))
```
Based on the blob == the config for the manifest, this is okay, but reading along the example I was expecting the blob to be a layer. I want to suggest renaming to something that explicitly contains config (e.g., configDigest / configBlob) so it's not confusing (I usually associate a blob with a layer, I'm not sure if this is just me). Feel free to disregard and close if you think it's okay as is. :)

**Comment by jdolitsky** [comment]
closing as old, please re-open if needed!
