### ISSUE TITLE
Digest calculation functions?

### ISSUE THREAD

**Issue by vsoch** [bloodorangeio/reggie#27]
Do you think the library has scope to provide functions to easily calculate digests, based on some binary? For all implementations so far I've had to roll my own digest functions, which isn't hugely complicated, but it seems like it should be easier.

**Comment by jdolitsky** [comment]
sorry for late response - would not be opposed. This library is however commonly used in Go: https://github.com/opencontainers/go-digest

Maybe some wrappers and a matching Python API? Do you have this baked into the library?

**Comment by vsoch** [comment]
I sort of matched those functions in https://github.com/vsoch/oci-python/tree/master/opencontainers/digest but it's fairly simple to just use hashlib in Python, I provide this example to the user (scroll down to import of hashlib) https://github.com/vsoch/oci-python/blob/ef31c76e524a419f683dd1ee5545ca4ad707fddb/docs/_docs/getting-started.md#upload-a-blob. 

Since this is an extra step for the user to use another library (I guess not a big deal, it's standard in Python) I'm wondering if this calculation should be handled by reggie.

**Comment by vsoch** [comment]
And no worries! I started a new job February 1st so I've been happily busy. :smile:

**Comment by jdolitsky** [comment]
closing as old, please re-open if needed!
