### ISSUE TITLE
Questions for Reggie "specification"

### ISSUE THREAD

**Issue by vsoch** [bloodorangeio/reggie#28]
The following questions are related to translating the reggie client to python-reggie here for the distribution spec.

- GetAbsoluteLocation can return nil/None,while Get RelativeLocation returns an empty string. Is this intentional? My thinking is that it would be logical for them to be consistent.
- For response.Errors it seems to be important that Errors is defined *and* not empty. Is it okay if Errors is not defined? Wouldn't a response without errors not pass along this attribute? I'd like to return an empty list either way, and the only real check is if the json parses. And even in that case, couldn't a response come back from a registry without any content to parse?
 - is HEAD a valid request for a distribution registry? 
 - For the original implementation, it seems to be allowed to create a [client with a bad address](https://github.com/bloodorangeio/reggie/blob/87668d9bb73e2d3655a6bb6d4127f86f51cbc066/client_test.go#L206) but for my version I validate this right away so I'm not able to do that full test.

**Comment by jdolitsky** [comment]
> GetAbsoluteLocation can return nil/None,while Get RelativeLocation returns an empty string. Is this intentional? My thinking is that it would be logical for them to be consistent.

No, I'd consider this a bug

> For response.Errors it seems to be important that Errors is defined and not empty

I'm not sure best thing to do here. In Go, its typical to check for `if x != nil`, so I'm not sure its incorrect

> is HEAD a valid request for a distribution registry

Yes. It was recently added officially to the http call table

> it seems to be allowed to create a client with a bad address

I'm not quite sure I follow... Are you not. passing a string to constructor?

**Comment by vsoch** [comment]
>  GetAbsoluteLocation can return nil/None,while Get RelativeLocation returns an empty string. Is this intentional? My thinking is that it would be logical for them to be consistent.

Gotcha! I'll take a look this weekend at the first bullet (inconsistent return values) and see if I can do a PR. (we can use this issue to track since it's already open)

> I'm not sure best thing to do here. In Go, its typical to check for if x != nil, so I'm not sure its incorrect

I totally don't remember what I was asking here!

>    it seems to be allowed to create a client with a bad address

For this one, I think I was caught up on the fact that you create a bad client (that triggers an error) and then keep interacting with it. In a real world use case, you'd probably stop at the error.

**Comment by jdolitsky** [comment]
Looks like the first one is addressed now. Lmk if we should keep this open, or open new tickets for the others

**Comment by vsoch** [comment]
I think that was the only address-able one, so I'm good to close :)
